# Generated by Django 5.1 on 2024-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
    ]
