# Generated by Django 5.1.3 on 2024-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Numero', models.CharField(max_length=100)),
                ('HorarioE', models.TimeField()),
                ('HorarioS', models.TimeField()),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
    ]
