# Generated by Django 5.1.2 on 2024-11-26 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provedor_app', '0003_alter_provedores_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedores',
            name='horario',
        ),
        migrations.AddField(
            model_name='provedores',
            name='HorarioE',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provedores',
            name='HorarioS',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
